//
// MinViewRangeType2.cs
//
// This file was generated by XMLSpy 2007r3 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace LayerSet
{

	public class MinViewRangeType2 : SchemaDouble
	{

		public MinViewRangeType2() : base()
		{
		}

		public MinViewRangeType2(string newValue) : base(newValue)
		{
			Validate();
		}

		public MinViewRangeType2(SchemaDouble newValue) : base(newValue)
		{
			Validate();
		}


		#region Documentation
		public static string GetAnnoDocumentation()
		{
			return "";
		}
		#endregion

		public  void Validate()
		{

			if (CompareTo(GetMaxInclusive()) > 0)
				throw new System.Exception("Value of MinViewRange is out of range.");

			if (CompareTo(GetMinInclusive()) < 0)
				throw new System.Exception("Value of MinViewRange is out of range.");
		}
		public  SchemaDouble GetMaxInclusive()
		{
			return new SchemaDouble("180");
		}
		public  SchemaDouble GetMinInclusive()
		{
			return new SchemaDouble("0");
		}
	}
}
