//
// RedType.cs
//
// This file was generated by XMLSpy 2007r3 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace LayerSet
{

	public class RedType : SchemaInt
	{

		public RedType() : base()
		{
		}

		public RedType(string newValue) : base(newValue)
		{
			Validate();
		}

		public RedType(SchemaInt newValue) : base(newValue)
		{
			Validate();
		}


		#region Documentation
		public static string GetAnnoDocumentation()
		{
			return "";
		}
		#endregion

		public  void Validate()
		{

			if (CompareTo(GetMaxInclusive()) > 0)
				throw new System.Exception("Value of Red is out of range.");

			if (CompareTo(GetMinInclusive()) < 0)
				throw new System.Exception("Value of Red is out of range.");
		}
		public  SchemaInt GetMaxInclusive()
		{
			return new SchemaInt("255");
		}
		public  SchemaInt GetMinInclusive()
		{
			return new SchemaInt("0");
		}
	}
}
