// -----------------------------------------------------------------------------
// This file has been generated by DynamicAssemblyInfo.exe
// -----------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute("Geosoft Inc.")]
[assembly: AssemblyProductAttribute("Dapple")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2010")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("2.1.4.674")]
[assembly: AssemblyFileVersion("2.1.4.674")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyNameAttribute("")]
[assembly: ComVisible(false)]
