//
// builderdirectoryBaseType.cs
//
// This file was generated by XMLSpy 2007r3 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace dappleview
{
	public class builderdirectoryBaseType : Altova.Xml.Node
	{
		#region Documentation
		public static string GetAnnoDocumentation() { return ""; }
		#endregion

		#region Forward constructors

		public builderdirectoryBaseType() : base() { SetCollectionParents(); }

		public builderdirectoryBaseType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public builderdirectoryBaseType(XmlNode node) : base(node) { SetCollectionParents(); }
		public builderdirectoryBaseType(Altova.Xml.Node node) : base(node) { SetCollectionParents(); }
		public builderdirectoryBaseType(Altova.Xml.Document doc, string namespaceURI, string prefix, string name) : base(doc, namespaceURI, prefix, name) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{
		}

		public void SetXsiType()
		{
 			XmlElement el = (XmlElement) domNode;
			el.SetAttribute("type", "http://www.w3.org/2001/XMLSchema-instance", "builderdirectoryBaseType");
		}


        private void SetCollectionParents()
        {
	}
}
}
