//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapple.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dapple.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon _3dxicon {
            get {
                object obj = ResourceManager.GetObject("_3dxicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addserver {
            get {
                object obj = ResourceManager.GetObject("addserver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Minimum X,Minimum Y,Maximum X,Maximum Y,Coordinate System
        ///Afghanistan,60.549075,29.40106,74.916112,38.401673,WGS 84
        ///Albania,19.291174,39.658327,21.08184,42.665859,WGS 84
        ///Algeria,-8.668257,19.149833,11.981782,36.917518,WGS 84
        ///American Samoa,-170.15314,-14.433602,-169.871949,-14.290644,WGS 84
        ///Andorra,1.427511,42.437628,1.725324,42.66056,WGS 84
        ///Angola,11.756476,-17.952889,23.998623,-4.485261,WGS 84
        ///Anguilla,-63.168392,18.163797,-62.970062,18.276025,WGS 84
        ///Antarctica,-179.9854,-89.901447,180.823514 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_region {
            get {
                return ResourceManager.GetString("aoi_region", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon arcims {
            get {
                object obj = ResourceManager.GetObject("arcims", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_marble {
            get {
                object obj = ResourceManager.GetObject("blue_marble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_marble_checked {
            get {
                object obj = ResourceManager.GetObject("blue_marble_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_marble_unchecked {
            get {
                object obj = ResourceManager.GetObject("blue_marble_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap {
            get {
                object obj = ResourceManager.GetObject("dap", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dap_18x18 {
            get {
                object obj = ResourceManager.GetObject("dap_18x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_database {
            get {
                object obj = ResourceManager.GetObject("dap_database", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_document {
            get {
                object obj = ResourceManager.GetObject("dap_document", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_gray {
            get {
                object obj = ResourceManager.GetObject("dap_gray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_grid {
            get {
                object obj = ResourceManager.GetObject("dap_grid", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_map {
            get {
                object obj = ResourceManager.GetObject("dap_map", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_picture {
            get {
                object obj = ResourceManager.GetObject("dap_picture", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_point {
            get {
                object obj = ResourceManager.GetObject("dap_point", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_spf {
            get {
                object obj = ResourceManager.GetObject("dap_spf", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap_voxel {
            get {
                object obj = ResourceManager.GetObject("dap_voxel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dapple {
            get {
                object obj = ResourceManager.GetObject("dapple", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dapplesplash {
            get {
                object obj = ResourceManager.GetObject("dapplesplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disserver {
            get {
                object obj = ResourceManager.GetObject("disserver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_view {
            get {
                object obj = ResourceManager.GetObject("email_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap enserver {
            get {
                object obj = ResourceManager.GetObject("enserver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_clear {
            get {
                object obj = ResourceManager.GetObject("filter_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_gray {
            get {
                object obj = ResourceManager.GetObject("folder_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon georef_image {
            get {
                object obj = ResourceManager.GetObject("georef_image", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_server_18x18 {
            get {
                object obj = ResourceManager.GetObject("image_server_18x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon kml {
            get {
                object obj = ResourceManager.GetObject("kml", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon layer {
            get {
                object obj = ResourceManager.GetObject("layer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_add {
            get {
                object obj = ResourceManager.GetObject("layers_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_bottom {
            get {
                object obj = ResourceManager.GetObject("layers_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_down {
            get {
                object obj = ResourceManager.GetObject("layers_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_download {
            get {
                object obj = ResourceManager.GetObject("layers_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_goto {
            get {
                object obj = ResourceManager.GetObject("layers_goto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_remove {
            get {
                object obj = ResourceManager.GetObject("layers_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_remove_all {
            get {
                object obj = ResourceManager.GetObject("layers_remove_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_removeallothers {
            get {
                object obj = ResourceManager.GetObject("layers_removeallothers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_top {
            get {
                object obj = ResourceManager.GetObject("layers_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layers_up {
            get {
                object obj = ResourceManager.GetObject("layers_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap led_off {
            get {
                object obj = ResourceManager.GetObject("led_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon led_off_icon {
            get {
                object obj = ResourceManager.GetObject("led_off_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap led_on {
            get {
                object obj = ResourceManager.GetObject("led_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon led_on_icon {
            get {
                object obj = ResourceManager.GetObject("led_on_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap legend {
            get {
                object obj = ResourceManager.GetObject("legend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon live {
            get {
                object obj = ResourceManager.GetObject("live", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon marble_icon {
            get {
                object obj = ResourceManager.GetObject("marble_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap metadata {
            get {
                object obj = ResourceManager.GetObject("metadata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon nasa {
            get {
                object obj = ResourceManager.GetObject("nasa", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_earth {
            get {
                object obj = ResourceManager.GetObject("nav_earth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_north {
            get {
                object obj = ResourceManager.GetObject("nav_north", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_rotate_left {
            get {
                object obj = ResourceManager.GetObject("nav_rotate_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_rotate_right {
            get {
                object obj = ResourceManager.GetObject("nav_rotate_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_tilt_down {
            get {
                object obj = ResourceManager.GetObject("nav_tilt_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_tilt_reset {
            get {
                object obj = ResourceManager.GetObject("nav_tilt_reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_tilt_up {
            get {
                object obj = ResourceManager.GetObject("nav_tilt_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_zoom_in {
            get {
                object obj = ResourceManager.GetObject("nav_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_zoom_out {
            get {
                object obj = ResourceManager.GetObject("nav_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon offline {
            get {
                object obj = ResourceManager.GetObject("offline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openview {
            get {
                object obj = ResourceManager.GetObject("openview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap properties {
            get {
                object obj = ResourceManager.GetObject("properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_cache {
            get {
                object obj = ResourceManager.GetObject("refresh_cache", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reset_dapple_defaults {
            get {
                object obj = ResourceManager.GetObject("reset_dapple_defaults", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveview {
            get {
                object obj = ResourceManager.GetObject("saveview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_intersecting {
            get {
                object obj = ResourceManager.GetObject("search_intersecting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_none {
            get {
                object obj = ResourceManager.GetObject("search_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_text {
            get {
                object obj = ResourceManager.GetObject("search_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_favourite {
            get {
                object obj = ResourceManager.GetObject("server_favourite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_refresh {
            get {
                object obj = ResourceManager.GetObject("server_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_remove {
            get {
                object obj = ResourceManager.GetObject("server_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snapshot {
            get {
                object obj = ResourceManager.GetObject("snapshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_list {
            get {
                object obj = ResourceManager.GetObject("tab_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_thumbnail {
            get {
                object obj = ResourceManager.GetObject("tab_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_tree {
            get {
                object obj = ResourceManager.GetObject("tab_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon tile {
            get {
                object obj = ResourceManager.GetObject("tile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tile_gray {
            get {
                object obj = ResourceManager.GetObject("tile_gray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap time {
            get {
                object obj = ResourceManager.GetObject("time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon time_icon {
            get {
                object obj = ResourceManager.GetObject("time_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trackbutton {
            get {
                object obj = ResourceManager.GetObject("trackbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trackbutton_disable {
            get {
                object obj = ResourceManager.GetObject("trackbutton_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon usgs {
            get {
                object obj = ResourceManager.GetObject("usgs", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vertical_exag {
            get {
                object obj = ResourceManager.GetObject("vertical_exag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_home {
            get {
                object obj = ResourceManager.GetObject("view_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_save {
            get {
                object obj = ResourceManager.GetObject("view_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon wms {
            get {
                object obj = ResourceManager.GetObject("wms", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wms_18x18 {
            get {
                object obj = ResourceManager.GetObject("wms_18x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon wms_gray {
            get {
                object obj = ResourceManager.GetObject("wms_gray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon worldwind_central {
            get {
                object obj = ResourceManager.GetObject("worldwind_central", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
