// ------------------------------------------------------------------------------- 
// General information about Geosoft assemblies: Generated by genbuild.pl script
// ------------------------------------------------------------------------------- 

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute("Geosoft Inc.")]
[assembly: AssemblyProductAttribute("Dapple")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2008")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("3.0.0.2")]
[assembly: AssemblyFileVersion("3.0.0.2")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyNameAttribute("")]
[assembly: ComVisible(false)]

