//
// WMS_MS_CapabilitiesDoc.cs
//
// This file was generated by XMLSpy 2007r3 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace WMS_MS_Capabilities
{
	public class WMS_MS_CapabilitiesDoc : Altova.Xml.Document
	{
		override internal protected void DeclareNamespaces(Altova.Xml.Node node)
		{
			DeclareNamespace(node, "xlink", "http://www.w3.org/1999/xlink");
			DeclareNamespace(node, "xml", "http://www.w3.org/XML/1998/namespace");
		}
	}
}
