//
// capabilities_1_3_0Doc.cs
//
// This file was generated by XMLSpy 2007r3 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace capabilities_1_3_0
{
	public class capabilities_1_3_0Doc : Altova.Xml.Document
	{
		override internal protected void DeclareNamespaces(Altova.Xml.Node node)
		{
			DeclareNamespace(node, "wms", "http://www.opengis.net/wms");
			DeclareNamespace(node, "xlink", "http://www.w3.org/1999/xlink");
		}
	}
}
